### ISSUE TITLE
Error on module.js:473 

### ISSUE THREAD

**Issue by Novel-Idea** [ktrzonkowski/soulbot#10]
My version will no longer run. I've updated to npm/node 8.0, but I continue to get the following error. 

> C:\Users\Administrator\Documents\GitHub>node soulbot.js
> module.js:473
>       throw err;
>       ^
> 
> Error: Cannot find module 'C:\Users\Administrator\Documents\GitHub\soulbot.js'
>     at Function.Module._resolveFilename (module.js:527:15)
>     at Function.Module._load (module.js:453:25)
>     at Function.Module.runMain (module.js:665:10)
>     at startup (bootstrap_node.js:201:16)
>     at bootstrap_node.js:626:3

**Comment by ktrzonkowski** [comment]
Sorry; soulbot.js was renamed to app.js to try to conform to more "normal" naming standards.
