### ISSUE TITLE
Soulbot Nonresponsive except for dA Command

### ISSUE THREAD

**Issue by Novel-Idea** [ktrzonkowski/soulbot#9]
While dA command still works perfectly, all other responses are no longer working. I've already checked using the old Common File that SoulBot is properly pulling the data below.

Note: This occured after adding my version (Philomena) to another server, specifically for the dA functionality. I'm unsure why it's claiming "blizzardbronies" as the home when Novel's Nook was the original and how this is causing any change. The config.json has not changed. 

C:\Users\Administrator\Documents\GitHub>node soulbot.js
Logged in as Philomena (361913248708296704)
No matter who I am logged in as, I am still SoulBot at heart.
My home is blizzardbronies, but I am also hanging out in:
 - Novel's Nook
RAW DATA FOR basicResponses
[ '*Despite what Sunset says, I\'ll have you know I\'m a perfectly normal semi-immortal phoenix.*',
  '*Sorry, I don\'t do owl impersonations.*',
  '*No, I wasn\'t playing with my Sunset and Twilight plushies again!*',
  '*Eep! It was on fire when I got there! I promise!*',
  '*Seriously, Novel couldn\'t have done better than this line? This is just lazy.*',
  '*You know, I was just talking to Celestia about how amazing you are! It was a short conversation.*',
  '*I swore I told Raven to hold all my calls. Yes?*',
  '*Excuse me?! Do I interrupt you when you\'re trying to burst into flame?!*',
  '*If you\'re in this server, you should probably be writing right now instead of playing with the birdie.*',
  '*Ssh! I\'m reading The Enchanted Library! Go bug SweetieBot!*',
  '!sunlight *There! Now, if you don\'t mind, I\'d like to finish my preening!*',
  '!fics *You\'re obviously looking for something to do. Go read this!*',
  '*I\'ll have you know I\'m the best thing Novel\'s ever written. Ever.*',
  '*All hail the true Archmage of SunLig--OW! NOVEL STOP HITTING ME!*',
  '*No, I don\'t feel like explaining why I have SciTwi and Princess Twi plushies snuggled next to my Sunset one!*',
  '*It\'s not easy keeping Celestia\'s little ponies in line. How many apprentices does one sun horse need anyway?!*',
  '*You\'re lucky Novel set up this phoenixsong translator.*',
  '*Hm. Yeah?*',
  '!celestia *I\'m contractually obligated to show you this picture.*',
  '*No, I have never stolen any of Sunset\'s books. Why do you ask?*',
  'Chirp, chirp. *There, you happy?*',
  '*You\'re adorable! I think we\'ll keep you around.*',
  '*Celestia said I should work on my diplomatic skills. Does this count?*',
  '*For the record, yes. I do hate tomato soup.*',
  '*For the last time, Celestia made me swear to never tell the truth behind \'Prince\' Blueblood!*',
  '*Fine, I admit Themis may be cuter, but I\'m still cooler.*',
  '*For the last time, I do NOT have a crush on Elara!*',
  '*I wonder when Elara and Themis will let me chicksit again...*' ]
PARSED DATA FOR basicResponses
[ '*Despite what Sunset says, I\'ll have you know I\'m a perfectly normal semi-immortal phoenix.*',
  '*Sorry, I don\'t do owl impersonations.*',
  '*No, I wasn\'t playing with my Sunset and Twilight plushies again!*',
  '*Eep! It was on fire when I got there! I promise!*',
  '*Seriously, Novel couldn\'t have done better than this line? This is just lazy.*',
  '*You know, I was just talking to Celestia about how amazing you are! It was a short conversation.*',
  '*I swore I told Raven to hold all my calls. Yes?*',
  '*Excuse me?! Do I interrupt you when you\'re trying to burst into flame?!*',
  '*If you\'re in this server, you should probably be writing right now instead of playing with the birdie.*',
  '*Ssh! I\'m reading The Enchanted Library! Go bug SweetieBot!*',
  '!sunlight *There! Now, if you don\'t mind, I\'d like to finish my preening!*',
  '!fics *You\'re obviously looking for something to do. Go read this!*',
  '*I\'ll have you know I\'m the best thing Novel\'s ever written. Ever.*',
  '*All hail the true Archmage of SunLig--OW! NOVEL STOP HITTING ME!*',
  '*No, I don\'t feel like explaining why I have SciTwi and Princess Twi plushies snuggled next to my Sunset one!*',
  '*It\'s not easy keeping Celestia\'s little ponies in line. How many apprentices does one sun horse need anyway?!*',
  '*You\'re lucky Novel set up this phoenixsong translator.*',
  '*Hm. Yeah?*',
  '!celestia *I\'m contractually obligated to show you this picture.*',
  '*No, I have never stolen any of Sunset\'s books. Why do you ask?*',
  'Chirp, chirp. *There, you happy?*',
  '*You\'re adorable! I think we\'ll keep you around.*',
  '*Celestia said I should work on my diplomatic skills. Does this count?*',
  '*For the record, yes. I do hate tomato soup.*',
  '*For the last time, Celestia made me swear to never tell the truth behind \'Prince\' Blueblood!*',
  '*Fine, I admit Themis may be cuter, but I\'m still cooler.*',
  '*For the last time, I do NOT have a crush on Elara!*',
  '*I wonder when Elara and Themis will let me chicksit again...*' ]
RAW DATA FOR userResponses
{ '157642037275918336':
   [ '*Novel! Why are you bothering me? You should be writing!*',
     '*You know, we\'re still waiting for the next chapter of Prerogative.*',
     '*I\'m still waiting for more stories about me, you know.*',
     '*For the last time, I\'m not going to write the story for you!*',
     '*You\'re bothering me while you\'re at work again, aren\'t you?*',
     '*I\'ve already turned to ash three times this week for you! Go ask Faerana if you need another inspiration hit!*',
     '*Why can\'t you bother Faerana instead of me? You\'re the one who wrote her all formal and stuff.*',
     '*By the Sunmother, Novel, get back to writing!*',
     '!writing *There Novel! Now go back to Scrivener!*',
     '!write *Sunset and Twilight said you needed this.*' ],
  '121510915903324162':
   [ '*Novel warned me about you.*',
     '!writing *There you go. Now back to work!*',
     '!write *Hey, we\'re all waiting for Spectacular Seven! Come on! Don\'t leave us hanging!*',
     '*You did know the Firebird Dahlias are actually named after me, right?*',
     '*Hey, I\'m still annoyed at you that I didn\'t get a big role in Sunset of Time!*',
     '*So, your Sunny tends to end up with the human Twi? Huh. That\'s a little weird.*' ] }
PARSED DATA FOR userResponses
[  ]
RAW DATA FOR userResponses
{ '157642037275918336':
   [ '*Novel! Why are you bothering me? You should be writing!*',
     '*You know, we\'re still waiting for the next chapter of Prerogative.*',
     '*I\'m still waiting for more stories about me, you know.*',
     '*For the last time, I\'m not going to write the story for you!*',
     '*You\'re bothering me while you\'re at work again, aren\'t you?*',
     '*I\'ve already turned to ash three times this week for you! Go ask Faerana if you need another inspiration hit!*',
     '*Why can\'t you bother Faerana instead of me? You\'re the one who wrote her all formal and stuff.*',
     '*By the Sunmother, Novel, get back to writing!*',
     '!writing *There Novel! Now go back to Scrivener!*',
     '!write *Sunset and Twilight said you needed this.*' ],
  '121510915903324162':
   [ '*Novel warned me about you.*',
     '!writing *There you go. Now back to work!*',
     '!write *Hey, we\'re all waiting for Spectacular Seven! Come on! Don\'t leave us hanging!*',
     '*You did know the Firebird Dahlias are actually named after me, right?*',
     '*Hey, I\'m still annoyed at you that I didn\'t get a big role in Sunset of Time!*',
     '*So, your Sunny tends to end up with the human Twi? Huh. That\'s a little weird.*' ] }
PARSED DATA FOR userResponses
[  ]
RAW DATA FOR groupResponses
{ 'Luminist Archmage':
   [ '*Novel said I\'m supposed to be nice to you. Any idea why?*',
     '!writing *You\'re one of those writer types, right? You\'ll probably like this.*',
     '*So, you\'re like... one of those senpais, right?*',
     '*So, how\'s the whole horsefame thing working for you?*',
     '!fics *So, is this one of yours?*' ],
  Storywalker:
   [ '*So, what horrible thing did Novel put you through today?*',
     '*Hey everypony! Be nice to this one! He\'s got to deal with Novel\'s madness way more than you.*',
     '*Is it really worth dealing with Novel\'s lunacy? Really?*',
     '*How drunk were you when you offered to edit for Novel, anyway?*' ],
  'Royal Treasurer':
   [ '*I\'ll definitely play nice with you. Most of the time.*',
     '*Your donation to the Phoenix Sass Fund is appreciated.*' ],
  'Pretty Picture Ponies':
   [ '*You should definitely be drawing more phoenixes.*',
     '*Yes, I\'d be more than happy to pose for you.*',
     '*Draw my like your French birdies.*' ],
  NaNos:
   [ '!write *Oooh! One of those really crazy writers!*',
     '!writing *So, what are you writing about today?*',
     '!write *You could never go wrong by adding me to your story. Just so you know.*',
     '!writing *Let\'s see if this gives you any inspiration.*',
     '!write *Yes, I\'d be more than happy to come into your story as a cameo. Just send the check to Celestia.*' ],
  'Temporal Explorer':
   [ '*Um... Novel never told me what a \'Temporal Explorer\' is... mind cluing me in?*',
     '*Why\'s your name blue?*',
     '*So, you\'ve got a blue name. Can you burst into flame whenever you want? Hm? That\'s what I thought!*' ],
  Voyager:
   [ '*Sweet! Another pony who likes to hop dimensions!*',
     '*So, why did Novel go with Oroboro\'s term anyway? Seems weird to me.*',
     '*You\'re not related to that starship I\'ve heard stories about... right?*',
     '!shipping *No, I wasn\'t going through Novel\'s ship collection again!*',
     '!philomena *Best bird. Right here.*' ] }
PARSED DATA FOR groupResponses
[ 'Luminist Archmage': [ '*Novel said I\'m supposed to be nice to you. Any idea why?*',
    '!writing *You\'re one of those writer types, right? You\'ll probably like this.*',
    '*So, you\'re like... one of those senpais, right?*',
    '*So, how\'s the whole horsefame thing working for you?*',
    '!fics *So, is this one of yours?*' ],
  Storywalker: [ '*So, what horrible thing did Novel put you through today?*',
    '*Hey everypony! Be nice to this one! He\'s got to deal with Novel\'s madness way more than you.*',
    '*Is it really worth dealing with Novel\'s lunacy? Really?*',
    '*How drunk were you when you offered to edit for Novel, anyway?*' ],
  'Royal Treasurer': [ '*I\'ll definitely play nice with you. Most of the time.*',
    '*Your donation to the Phoenix Sass Fund is appreciated.*' ],
  'Pretty Picture Ponies': [ '*You should definitely be drawing more phoenixes.*',
    '*Yes, I\'d be more than happy to pose for you.*',
    '*Draw my like your French birdies.*' ],
  NaNos: [ '!write *Oooh! One of those really crazy writers!*',
    '!writing *So, what are you writing about today?*',
    '!write *You could never go wrong by adding me to your story. Just so you know.*',
    '!writing *Let\'s see if this gives you any inspiration.*',
    '!write *Yes, I\'d be more than happy to come into your story as a cameo. Just send the check to Celestia.*' ],
  'Temporal Explorer': [ '*Um... Novel never told me what a \'Temporal Explorer\' is... mind cluing me in?*',
    '*Why\'s your name blue?*',
    '*So, you\'ve got a blue name. Can you burst into flame whenever you want? Hm? That\'s what I thought!*' ],
  Voyager: [ '*Sweet! Another pony who likes to hop dimensions!*',
    '*So, why did Novel go with Oroboro\'s term anyway? Seems weird to me.*',
    '*You\'re not related to that starship I\'ve heard stories about... right?*',
    '!shipping *No, I wasn\'t going through Novel\'s ship collection again!*',
    '!philomena *Best bird. Right here.*' ] ]
C:\Users\Administrator\Documents\GitHub\helpers\common.js:145
      return bot.server.members.get(userId).roles.get(bot.server.roles.find('name', checkRole).id) !== undefined || bot.server.members.get(userId).roles.get(checkRole) !== undefined;
                                                                                              ^

TypeError: Cannot read property 'id' of null
    at Object.memberHasRole (C:\Users\Administrator\Documents\GitHub\helpers\common.js:145:95)
    at Object.basicResponse (C:\Users\Administrator\Documents\GitHub\helpers\common.js:24:27)
    at Client.<anonymous> (C:\Users\Administrator\Documents\GitHub\soulbot.js:199:21)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\Administrator\Documents\GitHub\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\Administrator\Documents\GitHub\node_modules\ws\lib\EventTarget.js:99:16)

C:\Users\Administrator\Documents\GitHub>

**Comment by ktrzonkowski** [comment]
Turned out to be an issue with the home server not detecting correctly.  Fixed!
